[global]
type=global
user_agent=WaihuSystem-PoC

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=${ASTERISK_EXTERNAL_ADDRESS}
external_signaling_address=${ASTERISK_EXTERNAL_ADDRESS}

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=${ASTERISK_SIP_PASSWORD}

[1001]
type=endpoint
transport=transport-udp
context=from-test-phone
disallow=all
allow=ulaw,alaw
auth=1001-auth
aors=1001
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1001]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=30
