[general]
static=yes
writeprotect=no

[waihu-mobile]
exten => _X.,1,NoOp(Waihu outbound dialog ${EXTEN})
 same => n,Stasis(waihu-dialog,${EXTEN})
 same => n,Hangup()

[waihu-safe-hangup]
exten => s,1,NoOp(Waihu safe hangup)
 same => n,Hangup()

[waihu-ari-smoke]
exten => s,1,Answer()
 same => n,Wait(10)
 same => n,Hangup()
